language: rust

rust:
- stable
- beta
- nightly

script:
- cargo test --all
- cargo test --all --release

matrix:
  include:
  - name: cargo test
    os: osx

  - name: cargo test
    os: windows

  - name: cargo clippy
    install:
    - rustup component add clippy-preview
    script:
    - cargo clippy --all --all-targets -- -D warnings

  - name: cargo fmt
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt --all -- --check

  - name: diff src/thirdparty.rs
    script:
    - diff src/thirdparty.rs <(cargo run -- lichking bundle --variant source) || (
        echo 'Thirdparty license bundle out of date, please update with:';
        echo '    cargo run -- lichking bundle --variant source --file src/thirdparty.rs';
        exit 1
      )

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

branches:
  only: [staging, trying, master]
